### ISSUE TITLE
Notary token authentication issue

### ISSUE THREAD

**Issue by bbdtsof** [notaryproject/notary#1412]
Hello everyone,

I am struggling to get Notary token authentication to work. I'm using the latest version of the "notary:server" image and for authentication I have deployed the "cesanta/docker_auth:1". Notary's server configuration file looks like the following:
```
{
	"server": {
		"http_addr": ":5050"
	},
	"trust_service": {
		"type": "remote",
		"hostname": "signerhostname",
		"port": "5151",
		"tls_ca_file": "/cfg/root.crt",
		"key_algorithm": "ecdsa",
		"tls_client_cert": "/cfg/server.crt",
		"tls_client_key": "/cfg/server.key"
	},
	"auth": {
		"type": "token",
		"options": {
			"realm": "https://auth.service.com/auth",
			"service": "notary.test.com",
			"issuer": "auth.service.com",
			"rootcertbundle": "/cfg/auth.crt"
		}
	},
	"storage": {
		"backend": "mysql",
		"db_url": "server@tcp(mysql:3306)/notaryserverdb?parseTime=True"
	},
	"logging": {
		"level": "debug"
	}
} 
```
And docker_auth configuration looks like this:
```
# Server settings
server:
  addr: ":5252"

# Token settings
token:
  issuer: "auth.service.com"
  expiration: 300
  certificate: "/cfg/auth.pem"
  key: "/cfg/authkey.pem"

# Authentication method
users:
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfdsereewqlpkooxzjkljUadnkjhfo0imlkmsd"

# Authorization method
acl:
  - match: {account: "admin"}
    actions: ["*"]
    comment: "Admin has full access to everything."
```
Notary is working fine when I remove the authentication section from server's configuration file. Same applies for https://auth.service.com/auth - tokens are generated successfully.

When I enable docker content trust, set the "NOTARY_AUTH" env variable with "export NOTARY_AUTH=$(echo "admin:adminpassword" | base64)" and try to do docker push/pull or a simple notary list command it fails with "* fatal: unauthorized: authentication required". In Notary's server log I get:
```
{"go.version":"go1.10.5","http.request.host":"notary.test.com","http.request.id":"92e77c60-5e08-4288-9c4e-d0f21bf78356","http.request.method":"GET","http.request.remoteaddr":"xxx.xx.xx.xx","http.request.uri":"/v2/","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"147.289µs","http.response.status":401,"http.response.written":145,"level":"info","msg":"response completed","time":"2019-01-02T12:48:43Z"}
{"go.version":"go1.10.5","http.request.host":"notary.test.com","http.request.id":"386e4e99-1441-4954-ad9e-80e3a6fa2489","http.request.method":"GET","http.request.remoteaddr":"xxx.xx.xx.xx","http.request.uri":"/v2/","http.request.useragent":"Go-http-client/1.1","http.response.contenttype":"application/json; charset=utf-8","http.response.duration":"310.881µs","http.response.status":401,"http.response.written":145,"level":"info","msg":"response completed","time":"2019-01-02T12:48:51Z"}
```
My first question is does the configuration above look OK?

Also I saw this issue reported some time ago - "https://github.com/theupdateframework/notary/issues/1107" , but its still not clear for me how exactly the Notary and/or authentication endpoints should look like? I tried both https://notary.test.com/v2 and https://notary.test.com/v2/ and they both fail. The first one returns "you are not authorized to perform this operation: server returned 401." and the second one  "unable to reach trust server at this time: 301."

Thank you in advance!
