### ISSUE TITLE
Use Notary without TLS

### ISSUE THREAD

**Issue by IAL32** [notaryproject/notary#1614]
Related to #1230 

Would it be possible to setup Notary, server and signer, to not use any HTTPS at all? I am following the documentation for [server ](https://github.com/notaryproject/notary/blob/master/docs/reference/server-config.md) and [signer ](https://github.com/notaryproject/notary/blob/master/docs/reference/signer-config.md), which mentions:

| Parameter | Required | Description|
| :--: | :--: | :--: |
|`tls_key_file` | no | The path to the private key to use for HTTPS. Must be provided together with `tls_cert_file`, or not at all. If neither are provided, the server will use HTTP instead of HTTPS. The path is relative to the directory of the configuration file. |
| `tls_cert_file` | no |  The path to the certificate to use for HTTPS. Must be provided together with `tls_key_file`, or not at all. If neither are provided, the server will use HTTP instead of HTTPS. The path is relative to the directory of the configuration file. |

And the same goes for other parameters that specify cert files and keys. In theory, omitting these parameters will force the connection to use HTTP and not HTTPS.

However, if I omit these, I get the following error from the signer:

```json
{"level":"fatal","msg":"unable to set up TLS: Could not load X509 key pair (cert: \"\", key: \"\"): open : no such file or directory","time":"2021-10-05T20:17:41Z"}
```

This is my current configuration:

signer:
```json
{
  "server": {
    "grpc_addr": ":7899"
  },
  "logging": {
    "level": "debug"
  },
  "storage": {
    "backend": "postgres",
    "db_url": "postgres://signer@<postgres_host>:5432/notarysigner"
  }
}
```

server:

```json
{
 "server": {
  "http_addr": ":4443"
 },
 "trust_service": {
  "type": "remote",
  "hostname": "notarysigner",
  "port": "7899",
  "key_algorithm": "ecdsa"
 },
 "logging": {
  "level": "debug"
 },
 "storage": {
  "backend": "postgres",
  "db_url": "postgres://server@<postgres_host>:5432/notaryserver"
 }
}
```

docker-compose.postgresql.yml

```yml
version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    networks:
      - mdb
      - sig
    ports:
      - "8080"
      - "4443:4443"
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-server -config=fixtures/server-config.postgres.json"
    environment:
      MIGRATIONS_PATH: migrations/server/postgresql
      DB_URL: postgres://server@<postgres_host>:5432/notaryserver
    depends_on:
      - signer
  signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    networks:
      mdb:
      sig:
        aliases:
          - notarysigner
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-signer -config=fixtures/signer-config.postgres.json"
    environment:
      MIGRATIONS_PATH: migrations/signer/postgresql
      DB_URL: postgres://signer@<postgres_host>:5432/notarysigner
networks:
  mdb:
    external: false
  sig:
    external: false
```

I have a PostgreSQL server running in another instance, this is why I don't have it in my configuration. The connection between the database and Notary does not need encryption as well.

Please note that I don't want to enter a conversation about the need of having a secure connection. I know the downsides of not having the connection secured, but nevertheless, I need this configuration to work, as the documentation clearly states that it should be possible.

Thanks for the help!
